include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SendMyBatteryPrefs
SendMyBatteryPrefs_FILES = SMBRootListController.m
SendMyBatteryPrefs_FRAMEWORKS = UIKit
SendMyBatteryPrefs_PRIVATE_FRAMEWORKS = Preferences
SendMyBatteryPrefs_INSTALL_PATH = /Library/PreferenceBundles
SendMyBatteryPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
